#!/usr/bin/python

"""
stores tags for files


todo:

upgrade tag input to foaf:person, us city, wordnet word, etc.

see also:

http://www.kanzaki.com/test/exif2rdf

"""

import os, sys, urllib, time
from rdflib import Graph, URIRef, Namespace, RDF, Literal
from rdflib.util import date_time
from semfile import read_or_create_graph, graph_filename, FOAF, TAG, DC


graph = read_or_create_graph(graph_filename)

imgfile_uri = URIRef("file://%s" % os.path.abspath(sys.argv[1]))

graph.add((imgfile_uri, RDF.type, foaf['Image']))

tag_uri = URIRef(tagns+urllib.quote_plus(" ".join(sys.argv[2:])))
graph.add((imgfile_uri, foaf['topic'], tag_uri))

graph.save(graph_filename)

